services:
  # ============================================
  # REPORTS QUERY SERVICE (EMPTY)
  # ============================================
  reports-query:
    build:
      context: ./
      dockerfile: Dockerfile
    image: reports-query-service
    container_name: reports-query-service
    ports:
      - "4000:4000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: tickets_db
      PORT: 4000
    # depends_on:
      # postgres:
      #   condition: service_healthy
    restart: no
